# This file is part of DobryDom3D, a fork of Sweet Home 3D 7.5, modified by DobryDom3D contributors since August 2026.
extension=sh3d
mime-type=application/x-sweethome3d
description=SH3D home document
