# This file is part of DobryDom3D, a fork of Sweet Home 3D 7.5, modified by DobryDom3D contributors since August 2026.
extension=sh3l
mime-type=application/x-sweethome3d-language-library
description=SH3L language library
