# This file is part of DobryDom3D, a fork of Sweet Home 3D 7.5, modified by DobryDom3D contributors since August 2026.
extension=sh3p
mime-type=application/x-sweethome3d-plugin
description=SH3P plug-in
